# Generated by Django 4.0.6 on 2022-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('user_id', models.PositiveIntegerField()),
                ('store_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=6)),
                ('category_one_id', models.CharField(max_length=32)),
                ('category_url', models.CharField(max_length=1000)),
                ('platform_id', models.CharField(max_length=32)),
                ('pagination_type', models.CharField(max_length=50)),
                ('website_url', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
